apiVersion: v1
kind: Pod
metadata:
  name: discovery-server
  labels:
    app: ros2-discovery-server
spec:
  containers:
    - name: discovery-server
      image: master.harbor.registry/library/ubuntu-fastdds:v3.2.2
      imagePullPolicy: Always
      command: ["/bin/bash", "-c"]
      args:
        [
          "source /usr/local/eprosima/setup.bash && fastdds discovery -i 0 -p 11811",
        ]
      ports:
        - containerPort: 11811
          protocol: UDP
      env:
        - name: ROS_DOMAIN_ID
          value: "1"
        - name: FASTRTPS_LOG_LEVEL
          value: "INFO"
        - name: RMW_IMPLEMENTATION
          value: "rmw_fastrtps_cpp"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-svc
spec:
  clusterIP: None
  selector:
    app: ros2-discovery-server
  ports:
    - protocol: UDP
      port: 11811
      targetPort: 11811
