// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/configfile.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	configfile "github.com/linskybing/platform-go/internal/domain/configfile"
)

// MockConfigFileRepo is a mock of ConfigFileRepo interface.
type MockConfigFileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockConfigFileRepoMockRecorder
}

// MockConfigFileRepoMockRecorder is the mock recorder for MockConfigFileRepo.
type MockConfigFileRepoMockRecorder struct {
	mock *MockConfigFileRepo
}

// NewMockConfigFileRepo creates a new mock instance.
func NewMockConfigFileRepo(ctrl *gomock.Controller) *MockConfigFileRepo {
	mock := &MockConfigFileRepo{ctrl: ctrl}
	mock.recorder = &MockConfigFileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigFileRepo) EXPECT() *MockConfigFileRepoMockRecorder {
	return m.recorder
}

// CreateConfigFile mocks base method.
func (m *MockConfigFileRepo) CreateConfigFile(cf *configfile.ConfigFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfigFile", cf)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConfigFile indicates an expected call of CreateConfigFile.
func (mr *MockConfigFileRepoMockRecorder) CreateConfigFile(cf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfigFile", reflect.TypeOf((*MockConfigFileRepo)(nil).CreateConfigFile), cf)
}

// GetConfigFileByID mocks base method.
func (m *MockConfigFileRepo) GetConfigFileByID(id uint) (*configfile.ConfigFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigFileByID", id)
	ret0, _ := ret[0].(*configfile.ConfigFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigFileByID indicates an expected call of GetConfigFileByID.
func (mr *MockConfigFileRepoMockRecorder) GetConfigFileByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigFileByID", reflect.TypeOf((*MockConfigFileRepo)(nil).GetConfigFileByID), id)
}

// UpdateConfigFile mocks base method.
func (m *MockConfigFileRepo) UpdateConfigFile(cf *configfile.ConfigFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfigFile", cf)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfigFile indicates an expected call of UpdateConfigFile.
func (mr *MockConfigFileRepoMockRecorder) UpdateConfigFile(cf interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigFile", reflect.TypeOf((*MockConfigFileRepo)(nil).UpdateConfigFile), cf)
}

// DeleteConfigFile mocks base method.
func (m *MockConfigFileRepo) DeleteConfigFile(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfigFile", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfigFile indicates an expected call of DeleteConfigFile.
func (mr *MockConfigFileRepoMockRecorder) DeleteConfigFile(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfigFile", reflect.TypeOf((*MockConfigFileRepo)(nil).DeleteConfigFile), id)
}

// ListConfigFiles mocks base method.
func (m *MockConfigFileRepo) ListConfigFiles() ([]configfile.ConfigFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConfigFiles")
	ret0, _ := ret[0].([]configfile.ConfigFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConfigFiles indicates an expected call of ListConfigFiles.
func (mr *MockConfigFileRepoMockRecorder) ListConfigFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConfigFiles", reflect.TypeOf((*MockConfigFileRepo)(nil).ListConfigFiles))
}

// GetConfigFilesByProjectID mocks base method.
func (m *MockConfigFileRepo) GetConfigFilesByProjectID(projectID uint) ([]configfile.ConfigFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigFilesByProjectID", projectID)
	ret0, _ := ret[0].([]configfile.ConfigFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigFilesByProjectID indicates an expected call of GetConfigFilesByProjectID.
func (mr *MockConfigFileRepoMockRecorder) GetConfigFilesByProjectID(projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigFilesByProjectID", reflect.TypeOf((*MockConfigFileRepo)(nil).GetConfigFilesByProjectID), projectID)
}
