// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/job.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/job.go -destination=internal/repository/mock/job_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	job "github.com/linskybing/platform-go/internal/domain/job"
	repository "github.com/linskybing/platform-go/internal/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockJobRepo is a mock of JobRepo interface.
type MockJobRepo struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepoMockRecorder
	isgomock struct{}
}

// MockJobRepoMockRecorder is the mock recorder for MockJobRepo.
type MockJobRepoMockRecorder struct {
	mock *MockJobRepo
}

// NewMockJobRepo creates a new mock instance.
func NewMockJobRepo(ctrl *gomock.Controller) *MockJobRepo {
	mock := &MockJobRepo{ctrl: ctrl}
	mock.recorder = &MockJobRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepo) EXPECT() *MockJobRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJobRepo) Create(ctx context.Context, j *job.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobRepoMockRecorder) Create(ctx, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobRepo)(nil).Create), ctx, j)
}

// Get mocks base method.
func (m *MockJobRepo) Get(ctx context.Context, id string) (*job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJobRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJobRepo)(nil).Get), ctx, id)
}

// ListByProject mocks base method.
func (m *MockJobRepo) ListByProject(ctx context.Context, projectID string) ([]job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProject", ctx, projectID)
	ret0, _ := ret[0].([]job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProject indicates an expected call of ListByProject.
func (mr *MockJobRepoMockRecorder) ListByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProject", reflect.TypeOf((*MockJobRepo)(nil).ListByProject), ctx, projectID)
}

// ListByUser mocks base method.
func (m *MockJobRepo) ListByUser(ctx context.Context, userID string) ([]job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockJobRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockJobRepo)(nil).ListByUser), ctx, userID)
}

// UpdateStatus mocks base method.
func (m *MockJobRepo) UpdateStatus(ctx context.Context, id, status string, errorMsg *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockJobRepoMockRecorder) UpdateStatus(ctx, id, status, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockJobRepo)(nil).UpdateStatus), ctx, id, status, errorMsg)
}

// WithTx mocks base method.
func (m *MockJobRepo) WithTx(tx *gorm.DB) repository.JobRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.JobRepo)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockJobRepoMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockJobRepo)(nil).WithTx), tx)
}

// CountByUserProjectAndStatuses mocks base method.
func (m *MockJobRepo) CountByUserProjectAndStatuses(ctx context.Context, userID, projectID string, statuses []string) (int64, error) {
m.ctrl.T.Helper()
ret := m.ctrl.Call(m, "CountByUserProjectAndStatuses", ctx, userID, projectID, statuses)
ret0, _ := ret[0].(int64)
ret1, _ := ret[1].(error)
return ret0, ret1
}

// CountByUserProjectAndStatuses indicates an expected call of CountByUserProjectAndStatuses.
func (mr *MockJobRepoMockRecorder) CountByUserProjectAndStatuses(ctx, userID, projectID, statuses any) *gomock.Call {
mr.mock.ctrl.T.Helper()
return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserProjectAndStatuses", reflect.TypeOf((*MockJobRepo)(nil).CountByUserProjectAndStatuses), ctx, userID, projectID, statuses)
}

// ListByProjectAndStatuses mocks base method.
func (m *MockJobRepo) ListByProjectAndStatuses(ctx context.Context, projectID string, statuses []string) ([]job.Job, error) {
m.ctrl.T.Helper()
ret := m.ctrl.Call(m, "ListByProjectAndStatuses", ctx, projectID, statuses)
ret0, _ := ret[0].([]job.Job)
ret1, _ := ret[1].(error)
return ret0, ret1
}

// ListByProjectAndStatuses indicates an expected call of ListByProjectAndStatuses.
func (mr *MockJobRepoMockRecorder) ListByProjectAndStatuses(ctx, projectID, statuses any) *gomock.Call {
mr.mock.ctrl.T.Helper()
return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProjectAndStatuses", reflect.TypeOf((*MockJobRepo)(nil).ListByProjectAndStatuses), ctx, projectID, statuses)
}

// ListByStatus mocks base method.
func (m *MockJobRepo) ListByStatus(ctx context.Context, statuses []string) ([]job.Job, error) {
m.ctrl.T.Helper()
ret := m.ctrl.Call(m, "ListByStatus", ctx, statuses)
ret0, _ := ret[0].([]job.Job)
ret1, _ := ret[1].(error)
return ret0, ret1
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockJobRepoMockRecorder) ListByStatus(ctx, statuses any) *gomock.Call {
mr.mock.ctrl.T.Helper()
return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockJobRepo)(nil).ListByStatus), ctx, statuses)
}
