// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/project_pvc_binding.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/project_pvc_binding.go -destination=internal/repository/mock/project_pvc_binding_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/linskybing/platform-go/internal/domain/storage"
	repository "github.com/linskybing/platform-go/internal/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockProjectPVCBindingRepo is a mock of ProjectPVCBindingRepo interface.
type MockProjectPVCBindingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProjectPVCBindingRepoMockRecorder
	isgomock struct{}
}

// MockProjectPVCBindingRepoMockRecorder is the mock recorder for MockProjectPVCBindingRepo.
type MockProjectPVCBindingRepoMockRecorder struct {
	mock *MockProjectPVCBindingRepo
}

// NewMockProjectPVCBindingRepo creates a new mock instance.
func NewMockProjectPVCBindingRepo(ctrl *gomock.Controller) *MockProjectPVCBindingRepo {
	mock := &MockProjectPVCBindingRepo{ctrl: ctrl}
	mock.recorder = &MockProjectPVCBindingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectPVCBindingRepo) EXPECT() *MockProjectPVCBindingRepoMockRecorder {
	return m.recorder
}

// CreateBinding mocks base method.
func (m *MockProjectPVCBindingRepo) CreateBinding(ctx context.Context, binding *storage.ProjectPVCBinding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBinding", ctx, binding)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBinding indicates an expected call of CreateBinding.
func (mr *MockProjectPVCBindingRepoMockRecorder) CreateBinding(ctx, binding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBinding", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).CreateBinding), ctx, binding)
}

// DeleteBinding mocks base method.
func (m *MockProjectPVCBindingRepo) DeleteBinding(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBinding", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBinding indicates an expected call of DeleteBinding.
func (mr *MockProjectPVCBindingRepoMockRecorder) DeleteBinding(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBinding", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).DeleteBinding), ctx, id)
}

// DeleteBindingByProjectPVC mocks base method.
func (m *MockProjectPVCBindingRepo) DeleteBindingByProjectPVC(ctx context.Context, namespace, pvcName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBindingByProjectPVC", ctx, namespace, pvcName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBindingByProjectPVC indicates an expected call of DeleteBindingByProjectPVC.
func (mr *MockProjectPVCBindingRepoMockRecorder) DeleteBindingByProjectPVC(ctx, namespace, pvcName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBindingByProjectPVC", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).DeleteBindingByProjectPVC), ctx, namespace, pvcName)
}

// GetBinding mocks base method.
func (m *MockProjectPVCBindingRepo) GetBinding(ctx context.Context, id string) (*storage.ProjectPVCBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinding", ctx, id)
	ret0, _ := ret[0].(*storage.ProjectPVCBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinding indicates an expected call of GetBinding.
func (mr *MockProjectPVCBindingRepoMockRecorder) GetBinding(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinding", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).GetBinding), ctx, id)
}

// GetBindingByProjectPVC mocks base method.
func (m *MockProjectPVCBindingRepo) GetBindingByProjectPVC(ctx context.Context, namespace, pvcName string) (*storage.ProjectPVCBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBindingByProjectPVC", ctx, namespace, pvcName)
	ret0, _ := ret[0].(*storage.ProjectPVCBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBindingByProjectPVC indicates an expected call of GetBindingByProjectPVC.
func (mr *MockProjectPVCBindingRepoMockRecorder) GetBindingByProjectPVC(ctx, namespace, pvcName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBindingByProjectPVC", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).GetBindingByProjectPVC), ctx, namespace, pvcName)
}

// ListBindings mocks base method.
func (m *MockProjectPVCBindingRepo) ListBindings(ctx context.Context, projectID string) ([]storage.ProjectPVCBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBindings", ctx, projectID)
	ret0, _ := ret[0].([]storage.ProjectPVCBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBindings indicates an expected call of ListBindings.
func (mr *MockProjectPVCBindingRepoMockRecorder) ListBindings(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBindings", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).ListBindings), ctx, projectID)
}

// ListBindingsByGroupPVC mocks base method.
func (m *MockProjectPVCBindingRepo) ListBindingsByGroupPVC(ctx context.Context, groupPVCID string) ([]storage.ProjectPVCBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBindingsByGroupPVC", ctx, groupPVCID)
	ret0, _ := ret[0].([]storage.ProjectPVCBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBindingsByGroupPVC indicates an expected call of ListBindingsByGroupPVC.
func (mr *MockProjectPVCBindingRepoMockRecorder) ListBindingsByGroupPVC(ctx, groupPVCID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBindingsByGroupPVC", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).ListBindingsByGroupPVC), ctx, groupPVCID)
}

// ListBindingsByUser mocks base method.
func (m *MockProjectPVCBindingRepo) ListBindingsByUser(ctx context.Context, userID string) ([]storage.ProjectPVCBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBindingsByUser", ctx, userID)
	ret0, _ := ret[0].([]storage.ProjectPVCBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBindingsByUser indicates an expected call of ListBindingsByUser.
func (mr *MockProjectPVCBindingRepoMockRecorder) ListBindingsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBindingsByUser", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).ListBindingsByUser), ctx, userID)
}

// UpdateBinding mocks base method.
func (m *MockProjectPVCBindingRepo) UpdateBinding(ctx context.Context, binding *storage.ProjectPVCBinding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBinding", ctx, binding)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBinding indicates an expected call of UpdateBinding.
func (mr *MockProjectPVCBindingRepoMockRecorder) UpdateBinding(ctx, binding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBinding", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).UpdateBinding), ctx, binding)
}

// UpdateBindingStatus mocks base method.
func (m *MockProjectPVCBindingRepo) UpdateBindingStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBindingStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBindingStatus indicates an expected call of UpdateBindingStatus.
func (mr *MockProjectPVCBindingRepoMockRecorder) UpdateBindingStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBindingStatus", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).UpdateBindingStatus), ctx, id, status)
}

// WithTx mocks base method.
func (m *MockProjectPVCBindingRepo) WithTx(tx *gorm.DB) repository.ProjectPVCBindingRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.ProjectPVCBindingRepo)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockProjectPVCBindingRepoMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockProjectPVCBindingRepo)(nil).WithTx), tx)
}
