// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/resource.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	resource "github.com/linskybing/platform-go/internal/domain/resource"
)

// MockResourceRepo is a mock of ResourceRepo interface.
type MockResourceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockResourceRepoMockRecorder
}

// MockResourceRepoMockRecorder is the mock recorder for MockResourceRepo.
type MockResourceRepoMockRecorder struct {
	mock *MockResourceRepo
}

// NewMockResourceRepo creates a new mock instance.
func NewMockResourceRepo(ctrl *gomock.Controller) *MockResourceRepo {
	mock := &MockResourceRepo{ctrl: ctrl}
	mock.recorder = &MockResourceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceRepo) EXPECT() *MockResourceRepoMockRecorder {
	return m.recorder
}

// CreateResource mocks base method.
func (m *MockResourceRepo) CreateResource(resource *resource.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResource", resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateResource indicates an expected call of CreateResource.
func (mr *MockResourceRepoMockRecorder) CreateResource(resource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResource", reflect.TypeOf((*MockResourceRepo)(nil).CreateResource), resource)
}

// DeleteResource mocks base method.
func (m *MockResourceRepo) DeleteResource(rid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResource", rid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResource indicates an expected call of DeleteResource.
func (mr *MockResourceRepoMockRecorder) DeleteResource(rid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResource", reflect.TypeOf((*MockResourceRepo)(nil).DeleteResource), rid)
}

// GetResourceByConfigFileIDAndName mocks base method.
func (m *MockResourceRepo) GetResourceByConfigFileIDAndName(cfID uint, name string) (*resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceByConfigFileIDAndName", cfID, name)
	ret0, _ := ret[0].(*resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceByConfigFileIDAndName indicates an expected call of GetResourceByConfigFileIDAndName.
func (mr *MockResourceRepoMockRecorder) GetResourceByConfigFileIDAndName(cfID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceByConfigFileIDAndName", reflect.TypeOf((*MockResourceRepo)(nil).GetResourceByConfigFileIDAndName), cfID, name)
}

// GetResourceByID mocks base method.
func (m *MockResourceRepo) GetResourceByID(rid uint) (*resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceByID", rid)
	ret0, _ := ret[0].(*resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceByID indicates an expected call of GetResourceByID.
func (mr *MockResourceRepoMockRecorder) GetResourceByID(rid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceByID", reflect.TypeOf((*MockResourceRepo)(nil).GetResourceByID), rid)
}

// ListResourcesByConfigFileID mocks base method.
func (m *MockResourceRepo) ListResourcesByConfigFileID(cfID uint) ([]resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourcesByConfigFileID", cfID)
	ret0, _ := ret[0].([]resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResourcesByConfigFileID indicates an expected call of ListResourcesByConfigFileID.
func (mr *MockResourceRepoMockRecorder) ListResourcesByConfigFileID(cfID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourcesByConfigFileID", reflect.TypeOf((*MockResourceRepo)(nil).ListResourcesByConfigFileID), cfID)
}

// ListResourcesByProjectID mocks base method.
func (m *MockResourceRepo) ListResourcesByProjectID(pid uint) ([]resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourcesByProjectID", pid)
	ret0, _ := ret[0].([]resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResourcesByProjectID indicates an expected call of ListResourcesByProjectID.
func (mr *MockResourceRepoMockRecorder) ListResourcesByProjectID(pid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourcesByProjectID", reflect.TypeOf((*MockResourceRepo)(nil).ListResourcesByProjectID), pid)
}

// UpdateResource mocks base method.
func (m *MockResourceRepo) UpdateResource(resource *resource.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResource", resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateResource indicates an expected call of UpdateResource.
func (mr *MockResourceRepoMockRecorder) UpdateResource(resource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResource", reflect.TypeOf((*MockResourceRepo)(nil).UpdateResource), resource)
}
