// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/storage_permission.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/storage_permission.go -destination=internal/repository/mock/storage_permission_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storage "github.com/linskybing/platform-go/internal/domain/storage"
	repository "github.com/linskybing/platform-go/internal/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockStoragePermissionRepo is a mock of StoragePermissionRepo interface.
type MockStoragePermissionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStoragePermissionRepoMockRecorder
	isgomock struct{}
}

// MockStoragePermissionRepoMockRecorder is the mock recorder for MockStoragePermissionRepo.
type MockStoragePermissionRepoMockRecorder struct {
	mock *MockStoragePermissionRepo
}

// NewMockStoragePermissionRepo creates a new mock instance.
func NewMockStoragePermissionRepo(ctrl *gomock.Controller) *MockStoragePermissionRepo {
	mock := &MockStoragePermissionRepo{ctrl: ctrl}
	mock.recorder = &MockStoragePermissionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoragePermissionRepo) EXPECT() *MockStoragePermissionRepoMockRecorder {
	return m.recorder
}

// CreateAccessPolicy mocks base method.
func (m *MockStoragePermissionRepo) CreateAccessPolicy(ctx context.Context, policy *storage.GroupStorageAccessPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessPolicy", ctx, policy)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccessPolicy indicates an expected call of CreateAccessPolicy.
func (mr *MockStoragePermissionRepoMockRecorder) CreateAccessPolicy(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessPolicy", reflect.TypeOf((*MockStoragePermissionRepo)(nil).CreateAccessPolicy), ctx, policy)
}

// CreatePermission mocks base method.
func (m *MockStoragePermissionRepo) CreatePermission(ctx context.Context, perm *storage.GroupStoragePermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermission", ctx, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockStoragePermissionRepoMockRecorder) CreatePermission(ctx, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockStoragePermissionRepo)(nil).CreatePermission), ctx, perm)
}

// DeleteAccessPolicy mocks base method.
func (m *MockStoragePermissionRepo) DeleteAccessPolicy(ctx context.Context, pvcID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessPolicy", ctx, pvcID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessPolicy indicates an expected call of DeleteAccessPolicy.
func (mr *MockStoragePermissionRepoMockRecorder) DeleteAccessPolicy(ctx, pvcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPolicy", reflect.TypeOf((*MockStoragePermissionRepo)(nil).DeleteAccessPolicy), ctx, pvcID)
}

// DeletePermission mocks base method.
func (m *MockStoragePermissionRepo) DeletePermission(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermission", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermission indicates an expected call of DeletePermission.
func (mr *MockStoragePermissionRepoMockRecorder) DeletePermission(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermission", reflect.TypeOf((*MockStoragePermissionRepo)(nil).DeletePermission), ctx, id)
}

// GetAccessPolicy mocks base method.
func (m *MockStoragePermissionRepo) GetAccessPolicy(ctx context.Context, pvcID string) (*storage.GroupStorageAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessPolicy", ctx, pvcID)
	ret0, _ := ret[0].(*storage.GroupStorageAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessPolicy indicates an expected call of GetAccessPolicy.
func (mr *MockStoragePermissionRepoMockRecorder) GetAccessPolicy(ctx, pvcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessPolicy", reflect.TypeOf((*MockStoragePermissionRepo)(nil).GetAccessPolicy), ctx, pvcID)
}

// GetPermission mocks base method.
func (m *MockStoragePermissionRepo) GetPermission(ctx context.Context, groupID, userID, pvcID string) (*storage.GroupStoragePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermission", ctx, groupID, userID, pvcID)
	ret0, _ := ret[0].(*storage.GroupStoragePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermission indicates an expected call of GetPermission.
func (mr *MockStoragePermissionRepoMockRecorder) GetPermission(ctx, groupID, userID, pvcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermission", reflect.TypeOf((*MockStoragePermissionRepo)(nil).GetPermission), ctx, groupID, userID, pvcID)
}

// ListAccessPolicies mocks base method.
func (m *MockStoragePermissionRepo) ListAccessPolicies(ctx context.Context, groupID string) ([]storage.GroupStorageAccessPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessPolicies", ctx, groupID)
	ret0, _ := ret[0].([]storage.GroupStorageAccessPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessPolicies indicates an expected call of ListAccessPolicies.
func (mr *MockStoragePermissionRepoMockRecorder) ListAccessPolicies(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessPolicies", reflect.TypeOf((*MockStoragePermissionRepo)(nil).ListAccessPolicies), ctx, groupID)
}

// ListPermissions mocks base method.
func (m *MockStoragePermissionRepo) ListPermissions(ctx context.Context, groupID string) ([]storage.GroupStoragePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissions", ctx, groupID)
	ret0, _ := ret[0].([]storage.GroupStoragePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockStoragePermissionRepoMockRecorder) ListPermissions(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockStoragePermissionRepo)(nil).ListPermissions), ctx, groupID)
}

// ListPermissionsByPVC mocks base method.
func (m *MockStoragePermissionRepo) ListPermissionsByPVC(ctx context.Context, groupID, pvcID string) ([]storage.GroupStoragePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissionsByPVC", ctx, groupID, pvcID)
	ret0, _ := ret[0].([]storage.GroupStoragePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissionsByPVC indicates an expected call of ListPermissionsByPVC.
func (mr *MockStoragePermissionRepoMockRecorder) ListPermissionsByPVC(ctx, groupID, pvcID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissionsByPVC", reflect.TypeOf((*MockStoragePermissionRepo)(nil).ListPermissionsByPVC), ctx, groupID, pvcID)
}

// ListUserPermissions mocks base method.
func (m *MockStoragePermissionRepo) ListUserPermissions(ctx context.Context, userID string) ([]storage.GroupStoragePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserPermissions", ctx, userID)
	ret0, _ := ret[0].([]storage.GroupStoragePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserPermissions indicates an expected call of ListUserPermissions.
func (mr *MockStoragePermissionRepoMockRecorder) ListUserPermissions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserPermissions", reflect.TypeOf((*MockStoragePermissionRepo)(nil).ListUserPermissions), ctx, userID)
}

// RevokePermission mocks base method.
func (m *MockStoragePermissionRepo) RevokePermission(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokePermission", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokePermission indicates an expected call of RevokePermission.
func (mr *MockStoragePermissionRepoMockRecorder) RevokePermission(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokePermission", reflect.TypeOf((*MockStoragePermissionRepo)(nil).RevokePermission), ctx, id)
}

// UpdateAccessPolicy mocks base method.
func (m *MockStoragePermissionRepo) UpdateAccessPolicy(ctx context.Context, policy *storage.GroupStorageAccessPolicy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccessPolicy", ctx, policy)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccessPolicy indicates an expected call of UpdateAccessPolicy.
func (mr *MockStoragePermissionRepoMockRecorder) UpdateAccessPolicy(ctx, policy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccessPolicy", reflect.TypeOf((*MockStoragePermissionRepo)(nil).UpdateAccessPolicy), ctx, policy)
}

// UpdatePermission mocks base method.
func (m *MockStoragePermissionRepo) UpdatePermission(ctx context.Context, perm *storage.GroupStoragePermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermission", ctx, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePermission indicates an expected call of UpdatePermission.
func (mr *MockStoragePermissionRepoMockRecorder) UpdatePermission(ctx, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermission", reflect.TypeOf((*MockStoragePermissionRepo)(nil).UpdatePermission), ctx, perm)
}

// WithTx mocks base method.
func (m *MockStoragePermissionRepo) WithTx(tx *gorm.DB) repository.StoragePermissionRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.StoragePermissionRepo)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockStoragePermissionRepoMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockStoragePermissionRepo)(nil).WithTx), tx)
}
