// Code generated by MockGen. DO NOT EDIT.
// Source: ./repositories/audit_repository.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/linskybing/platform-go/src/models"
	repositories "github.com/linskybing/platform-go/src/repositories"
)

// MockAuditRepo is a mock of AuditRepo interface.
type MockAuditRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepoMockRecorder
}

// MockAuditRepoMockRecorder is the mock recorder for MockAuditRepo.
type MockAuditRepoMockRecorder struct {
	mock *MockAuditRepo
}

// NewMockAuditRepo creates a new mock instance.
func NewMockAuditRepo(ctrl *gomock.Controller) *MockAuditRepo {
	mock := &MockAuditRepo{ctrl: ctrl}
	mock.recorder = &MockAuditRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepo) EXPECT() *MockAuditRepoMockRecorder {
	return m.recorder
}

// CreateAuditLog mocks base method.
func (m *MockAuditRepo) CreateAuditLog(audit *models.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", audit)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockAuditRepoMockRecorder) CreateAuditLog(audit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockAuditRepo)(nil).CreateAuditLog), audit)
}

// GetAuditLogs mocks base method.
func (m *MockAuditRepo) GetAuditLogs(params repositories.AuditQueryParams) ([]models.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditLogs", params)
	ret0, _ := ret[0].([]models.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditLogs indicates an expected call of GetAuditLogs.
func (mr *MockAuditRepoMockRecorder) GetAuditLogs(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditLogs", reflect.TypeOf((*MockAuditRepo)(nil).GetAuditLogs), params)
}
